name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ewanskurt/nextjs-ecommerce:latest .
          docker push ewanskurt/nextjs-ecommerce:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ewanskurt/nextjs-ecommerce:latest
            docker stop nextjs-ecommerce || true
            docker rm nextjs-ecommerce || true
            docker run -d --name nextjs-ecommerce -p 3000:3000 ewanskurt/nextjs-ecommerce:latest
